# $Id$

all: docu

docu:
	doxygen doxygen_yavec.cfg

distclean: clean

clean:
	rm -rf html latex

maintainer-clean:
	rm -rf html latex

install:

uninstall:

.PHONY: all docu clean distclean maintainer-clean
